### ISSUE TITLE
ScriptInterface::popNumber(). Error: Expected an integer parameter.

### ISSUE THREAD

**Issue by hansjny** [tarantonio/avesta#1]
Hello! It seems to be a while since you worked on this. 

Did you get this issue when you compiled?
ScriptInterface::popNumber(). Error: Expected an integer parameter.

When I run your .exe, everything works smoothly. When I compile it myself, I get this error. 
Been stuck at it the whole day now, really can't figure that part out. 
@tarantonio Do you have any idea?

**Comment by tarantonio** [comment]
Can`t reproduce the error
Compiled again and works like a charm
Try to follow all steps carefully, maybe any missing step or something.

**Comment by hansjny** [comment]
Thanks for the reply, and sorry for the insanely late response! If it was unclear, the error does not occur upon compiling. The source compiles like a charm! But when running with the data pack that comes with the repo [this is the console dump](https://gist.github.com/hansjny/ae7a1a9d61b120a6efebf19a62052d71). 


Also the size of my binary is only 1275KB, while _Avesta.exe_ is some 1500KBs. I figured it could be because I have no icon, but I doubt it's only that as over 200KB seems a bit excessive for an icon. It looks to me that the binary attached (which runs like a charm) is not compiled with the source provided? The errors are obviously from lua scripts, and I guess it could be fixed by modifying those, but that doesn't really explain why it works with the provided _Avesta.exe_. Is it compiled with another luascript source file, maybe? 

Again, any help would be appreciated!


Edit: Another thing to note. My compiled binary tries to load globalevents and fails. Avesta.exe does not attempt to load it.

Edit 2: Ok, obviously the Avesta.exe is Avesta 0.6.4, while the compiled binary is 0.6.5. This lead me to believe the data pack is also for 0.6.4, while the source is for 0.6.5. I have been working with this data pack for a while, and would like to get 0.6.4 to work. You don't happen to have 0.6.4 sources?

**Comment by tarantonio** [comment]
Closing old issues
