### ISSUE TITLE
rsa antibot

### ISSUE THREAD

**Issue by Kuhicop** [tarantonio/avesta#2]
Hello, changing the RSA is the only way to make antibot client?
So people will be able to login my server only with my client?
Thanks in advance!

**Comment by hansjny** [comment]
Correct me if I'm wrong, but as far as I know changing the RSA only works for bots that sends packages for your client. For instance cavebotting, etc. If you want to prevent people from logging in with multiple clients, you have to do something else.

**Comment by Kuhicop** [comment]
I want to protect my server to make people use only my custom client

**Comment by hansjny** [comment]
If you only want people to use your server, you could change something in the communication protocol on the client and server side. For instance adding a byte in the beginning or end. If this byte is not there, simply close the connection. Of course it's easy enough to circumvent, but I doubt anyone will do the effort in an OT scenario. You could switch RSA, but I think it is well known how to replace RSA in client.

**Comment by tarantonio** [comment]
Closing this.
